name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: npm install vuepress-theme-reco --save-build && npm run docs:build
          BUILD_DIR: docs
          TARGET_REPO: mzqmountainn/docs
          TARGET_BRANCH: gh-pages
          COMMIT_MESSAGE: 自动打包完成
          #CNAME: blog.huankong.top
